root: true
extends: airbnb
rules:
  function-paren-newline: off
  max-len: off
  no-console: off
  no-else-return: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-unexpected-multiline: error
  prefer-destructuring: off
  semi:
    - error
    - never
plugins:
  - import
env:
  es6: true
  node: true
