root: true
extends: airbnb
rules:
  # Note: this is to prevent compile errors for Node < 8.x. When Node 6 is
  #   deprecated, this comma-dangle rule exception can be removed.
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: ignore
      exports: ignore
      functions: never
  function-paren-newline: off
  max-len: off
  no-console: off
  no-else-return: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-unexpected-multiline: error

  # TODO: Turn on these linting rules and fix violations
  import/extensions: off
  import/no-dynamic-require: off
  import/order: off
  global-require: off
  arrow-parens: off
  operator-linebreak: off
  lines-between-class-members: off
  prefer-object-spread: off
  function-call-argument-newline: off
  implicit-arrow-linebreak: off
  no-promise-executor-return: off
  # End TODO

  semi:
    - error
    - never
plugins:
  - import
env:
  es6: true
  node: true
