before_script:
  - printenv
  - echo
  - npm install

run-test:
  script:
    - npm run lint
    - npm test
    - npm run test-upgrade

aws-integration-test:
  script:
    - npm install -g serverless
    - creds-helper -aws
    - npm run test-integration
