before_script:
  - echo
  - npm install

run-test:
  script:
    - npm run lint
    - npm test
    - npm run test-upgrade

aws-integration-test:
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  variables:
    STAGE: test
  script:
    - creds-helper -aws
    - aws opsworks describe-my-user-profile
#    - npm run test-integration
    - mkdir slsart-test
    - cd slsart-test
    - slsart configure
    - slsart deploy
    - slsart invoke
    - slsart remove
