before_script:
  - echo
  - npm install

run-test:
  script:
    - npm run lint
    - npm test
    - npm run test-upgrade

aws-integration-test:
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  script:
    # Authenticate with AWS
    - creds-helper -aws

    # Create test project
    - mkdir slsart-test
    - cd slsart-test
    - slsart configure

    # Check the `script` and `update` commands
    - slsart script
    - slsart upgrade

    # Validate minimal use case is working
    - slsart deploy --stage test
    - slsart invoke --stage test
    - slsart remove --stage test

    # Clean up
    - cd ..
    - rm -rf slsart-test
