#!/usr/bin/env bash

if [ ! -d "./lib/lambda/node_modules" ]
then
  # Install node dependencies
  pushd ./lib/lambda || exit
  npm ci
  popd || return
fi

if [ ! -d "./tests/integration/target/node_modules" ]
then
  # Install node dependencies
  pushd ./tests/integration/target || exit
  npm ci
  popd || return
fi
